DEALERS = [
    {
        "id": 1,
        "full_name": "Prairie Star Motors",
        "city": "Topeka",
        "state": "Kansas",
        "address": "4100 SW 21st Street",
        "zip": "66604",
        "lat": 39.036,
        "long": -95.724,
        "short_name": "Prairie Star",
    },
    {
        "id": 2,
        "full_name": "Lakeside Auto Group",
        "city": "Chicago",
        "state": "Illinois",
        "address": "220 Lake Shore Drive",
        "zip": "60601",
        "lat": 41.886,
        "long": -87.614,
        "short_name": "Lakeside",
    },
    {
        "id": 3,
        "full_name": "Golden Gate Cars",
        "city": "San Francisco",
        "state": "California",
        "address": "88 Mission Street",
        "zip": "94105",
        "lat": 37.793,
        "long": -122.394,
        "short_name": "Golden Gate",
    },
]

REVIEWS = [
    {
        "id": 101,
        "dealership": 1,
        "name": "Avery Johnson",
        "purchase": True,
        "purchase_date": "2026-07-14",
        "review": "Fantastic services and quick paperwork.",
        "sentiment": "positive",
        "car_make": "Toyota",
        "car_model": "Camry",
        "car_year": 2024,
    },
    {
        "id": 102,
        "dealership": 1,
        "name": "Minh Tran",
        "purchase": False,
        "purchase_date": "2026-07-20",
        "review": "Friendly team and clear pricing.",
        "sentiment": "positive",
        "car_make": "Honda",
        "car_model": "Accord",
        "car_year": 2023,
    },
    {
        "id": 103,
        "dealership": 2,
        "name": "Jordan Lee",
        "purchase": True,
        "purchase_date": "2026-06-28",
        "review": "The service desk was helpful.",
        "sentiment": "positive",
        "car_make": "Ford",
        "car_model": "Escape",
        "car_year": 2022,
    },
]

CARS = [
    {"make": "Toyota", "models": ["Camry", "Corolla", "RAV4"]},
    {"make": "Honda", "models": ["Accord", "Civic", "CR-V"]},
    {"make": "Ford", "models": ["Escape", "F-150", "Explorer"]},
]

CAR_MODELS = [
    {"make": "Toyota", "model": "Camry"},
    {"make": "Toyota", "model": "Corolla"},
    {"make": "Toyota", "model": "RAV4"},
    {"make": "Toyota", "model": "Prius"},
    {"make": "Honda", "model": "Accord"},
    {"make": "Honda", "model": "Civic"},
    {"make": "Honda", "model": "CR-V"},
    {"make": "Honda", "model": "Pilot"},
    {"make": "Ford", "model": "Escape"},
    {"make": "Ford", "model": "F-150"},
    {"make": "Ford", "model": "Explorer"},
    {"make": "Ford", "model": "Mustang"},
    {"make": "Chevrolet", "model": "Malibu"},
    {"make": "Chevrolet", "model": "Tahoe"},
    {"make": "Nissan", "model": "Altima"},
]
